# settings.py
ROOM_SIZE = 40
WALL_HEIGHT = 6.0
WALL_THICKNESS = 0.2
DOOR_WIDTH = 2.0
DOOR_HEIGHT = 3.0
WINDOW_WIDTH = 1.5
WINDOW_HEIGHT = 1.5
WINDOW_Y = 1.8
PLAYER_MAX_HEALTH = 100
GRID_SIZE = 3   # размер сетки комнат